//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPR_UI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DicomDataSet\\PTCT\\Dataset1\\1.3.12.2.1107.5.1.4.1007.30000012032001413290600020" +
            "180")]
        public string CT_DICOM_DIR {
            get {
                return ((string)(this["CT_DICOM_DIR"]));
            }
            set {
                this["CT_DICOM_DIR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tomato")]
        public global::System.Drawing.Color AxialColor {
            get {
                return ((global::System.Drawing.Color)(this["AxialColor"]));
            }
            set {
                this["AxialColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlueViolet")]
        public global::System.Drawing.Color CoronalColor {
            get {
                return ((global::System.Drawing.Color)(this["CoronalColor"]));
            }
            set {
                this["CoronalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color SagittalColor {
            get {
                return ((global::System.Drawing.Color)(this["SagittalColor"]));
            }
            set {
                this["SagittalColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\DicomDataSet\\PTCT\\Dataset1\\1.3.12.2.1107.5.1.4.1007.30000012032001433800000011" +
            "963")]
        public string PT_DICOM_DIR {
            get {
                return ((string)(this["PT_DICOM_DIR"]));
            }
            set {
                this["PT_DICOM_DIR"] = value;
            }
        }
    }
}
